os:
  - linux
  - osx
  
language: cpp

compiler:
  - gcc
  - clang
  
env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

matrix:
  allow_failures:
  - os: osx 

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  cd ..; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; mkdir build_xcode; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; cd build_xcode; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. -GXcode -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install_xcode; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd ../build; fi

script:
  - make
  - make test
  - make install
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd ../build_xcode; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then xcodebuild; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then xcodebuild -target test; fi
